spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      names: ${job.names:NONE}
    jdbc:
      initialize-schema: always
